### ISSUE TITLE
hDevInfo.ToInt32() caused overflow exception. ToInt64() solved it.

### ISSUE THREAD

**Issue by HubKing** [Shinao/WinDeviceManagerLight#1]
I currently have not a 32-bit Windows device, so I cannot test whether this application runs correctly on a 32-bit device or not, but it caused exceptions on my 64-bit Windows devices.

I changed `ToInt32()` to `ToInt64()`, and it worked. Also, enabling/disable required administrative privilege. Without it, it did not work. So, it might be a good idea to show an error message like "Cannot enable/disable the device without administrative privilege."

**Comment by Shinao** [comment]
I also have a x64 machine, yet I have no problem running the application. Does running/compiling the project in x86 instead of AnyCPU/x64 works ?
Yep good idea on the administrator privilege info, I will add it.

**Comment by HubKing** [comment]
I cannot test that right now, but one thing I should mention is that I upgraded the projects' .Net version from 2.0 to 4.7. Windows version is 10 Creators' update.

**Comment by Shinao** [comment]
It was indeed a problem with the .Net version. I have made an update that took care of this problem by upgrading everything and added the administrator right check. Also put a device status in the list, not sure how stable it is yet but hey, it's something.
