### ISSUE TITLE
x64 vs x86 

### ISSUE THREAD

**Issue by JayMartin** [Shinao/WinDeviceManagerLight#2]
I want to integrate the class into an existing app that required 0x86 for historical purposes.  If I switch you app from x64 to x86, if fails to reset at the following line:
private bool ChangeIt(IntPtr hDevInfo, Native.SP_DEVINFO_DATA devInfoData, bool bEnable)
{
...
if (**Native.SetupDiSetClassInstallParams(hDevInfo, ptrToDevInfoData, ptrToPcp, Marshal.SizeOf(typeof(Native.SP_PROPCHANGE_PARAMS)**)))
                    {
                        Native.SetupDiCallClassInstaller(Native.DIF_PROPERTYCHANGE, hDevInfo, ptrToDevInfoData);
                   }
...
}

The "If" statement fails and the GetLastError returns an 87.    I'm guessing it may have to do with structure size, but wanted to run this by you to see if you've seen it.

Great class by the way :)  

Thanks,

J. Martin

**Comment by Shinao** [comment]
Hi there,

Indeed it should be the size, in `HardwareHelperLib.cs`, change all occurrences of `hDevInfo.ToInt64()` to `hDevInfo.ToInt32()`
If it still does not work, try to pull the repository to the first committed version `28f1a29868f97d08c94860ec47fb60171bad3d16`.

Tell me what works so that I can make the changes on the repo or investigate.

Thanks

**Comment by JayMartin** [comment]
This function fails... with a 13 (ERROR_INVALID_DATA)
Native.SetupDiGetDeviceRegistryProperty(hDevInfo, DeviceInfoData, Native.SPDRP_FRIENDLYNAME, 0, DeviceFriendlyName, Native.MAX_DEV_LEN, IntPtr.Zero)

Not sure why this works on 64 and not 32.  I'll keep looking for solution.

**Comment by JayMartin** [comment]
Above was incorrect.  I was able to get the proper info for the friendly name, but the failure occured on this line.  

Native.SetupDiCallClassInstaller(Native.DIF_PROPERTYCHANGE, hDevInfo, ptrToDevInfoData);

The return value is false and the GetLastError is 0, so I'm sort of stuck.

I'm running Win7 x64, and I'm in the Local Admins group.    Any other ideas?   It's gotta be something in the ChangeIt function.  I'm not 100% checked out on the marshaling of the params, so a little hesitant to start changing that code.  

Thanks for your help.
J.

**Comment by Shinao** [comment]
Have you tried both of the possible solutions that I said above ?
I've tried on my computer running W10, I've got no problem on x86 or x64.
I can't help much without reproducing the problem, you are going to have to fiddle with the code to make it work on your system.
